---
- hosts: all

  become: false
  gather_facts: true
  tasks:
    - name: Test Connection
      win_ping:
    - name: Warn logged in users of impending upgrade
      community.windows.win_msg:
        display_seconds: 60
        msg: Automated upgrade about to start.  Please save your work and log off before {{ deployment_start_time }}
