---
- hosts: all

  become: false
  gather_facts: false
  tasks:
    - name: Test Connection
      win_ping:
    - name: Ensure we wait long enough for the updates to be applied during reboot
      ansible.windows.win_updates:
        category_names: '*'
        reject_list:
          - KB5031364
          - KB5031361
        reboot: true
    - name: Remove a file, if present
      ansible.windows.win_file:
        path: C:\ansible_wu.txt
        state: absent
