---
- hosts: all

  become: false
  gather_facts: false
  tasks:
    - name: Test Connection
      win_ping:
    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt