---
- hosts: all

  become: false
  gather_facts: true
  tasks:
    - name: Test Connection
      win_ping:
    - name: Warn logged in users of impending upgrade
      community.windows.win_msg:
        display_seconds: 60
        msg: Automated upgrade about to start. Please save all your work and lock your computer. Thank you!

    - name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt
