- hosts: Servers
  become: false
  gather_facts: true
  tasks:
    - name: Test Connection on s1
      win_ping:

    - name: Warn logged in users on s1 of impending upgrade
      community.windows.win_msg:
        display_seconds: 60
        msg: Automated upgrade about to start on s1. Please save all your work and lock your computer. Thank you!

    - name: Search-only on s1, return list of found updates (if any), log to C:\ansible_wu.txt
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt

    - name: Install all updates and reboot on s1 as many times as needed
      ansible.windows.win_updates:
        category_names: "*"
        reboot: true
