---
- name: Install Wazuh and Sysmon
  hosts: all # Replace with the name of your Windows host group
  gather_facts: no
  tasks:
    - name: Copy Wazuh agent installer
      win_copy:
        src: "\\\\192.1.0.6\\General\\wazuh\\wazuh-agent.msi"
        dest: "{{ ansible_env.TEMP }}\\wazuh-agent.msi"
      become: yes

    - name: Install Wazuh agent
      win_command: msiexec.exe /i "{{ ansible_env.TEMP }}\\wazuh-agent.msi" /q WAZUH_MANAGER='192.1.3.216' WAZUH_REGISTRATION_PASSWORD='Fbcad2801' WAZUH_AGENT_GROUP='windows' WAZUH_REGISTRATION_SERVER='192.1.3.216'
      become: yes

    - name: Delete Wazuh agent installer
      win_shell: Remove-Item -Path "{{ ansible_env.TEMP }}\\wazuh-agent.msi" -Force
      become: yes

    - name: Copy Sysmon installer and config
      win_copy:
        src: "\\\\192.1.0.6\\General\\sysmon"
        dest: "{{ ansible_env.TEMP }}\\sysmon"
      become: yes

    - name: Install Sysmon
      win_command: "{{ ansible_env.TEMP }}\\sysmon\\sysmon64.exe -i {{ ansible_env.TEMP }}\\sysmon\\sysmon.xml"
      become: yes

    - name: Delete Sysmon installer
      win_shell: Remove-Item -Path "{{ ansible_env.TEMP }}\\sysmon" -Recurse -Force
      become: yes
