---
- name: Remove specified files and packages, and execute apt autoremove
  hosts: all
  become: yes

  tasks:
    # Remove wazuh.list file
    - name: Remove /etc/apt/sources.list.d/wazuh.list
      file:
        path: /etc/apt/sources.list.d/wazuh.list
        state: absent

    # Uninstall wazuh-indexer
    - name: Uninstall wazuh-indexer
      package:
        name: wazuh-indexer
        state: absent

    # Uninstall wazuh-dashboard
    - name: Uninstall wazuh-dashboard
      package:
        name: wazuh-dashboard
        state: absent

    # Uninstall fluent-bit
    - name: Uninstall fluent-bit
      package:
        name: fluent-bit
        state: absent

    # Uninstall graylog
    - name: Uninstall graylog-server
      package:
        name: graylog-server
        state: absent

    # Uninstall opensearch
    - name: Uninstall opensearch
      package:
        name: opensearch
        state: absent

    # Uninstall mongodb
    - name: Uninstall mongodb
      package:
        name: mongodb
        state: absent

    # Run apt autoremove
    - name: Run apt autoremove
      apt:
        autoremove: yes

    # Reboot the machine
    - name: Reboot the machine
      reboot:
        msg: "Rebooting after package removal"
        timeout: 600
        connect_timeout: 60
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: whoami
