- name: Setup Debian System and install NVM, Node.js, SNMP, and LLDPD
  hosts: all
  become: yes
  vars:
    node_version: "21.2.0" # Change to your desired Node.js version
    packages:
      - cockpit-pcp
      - lm-sensors
      - snmpd
      - snmp
      - lldpd
      - curl
      - build-essential
      - libssl-dev
      - gnupg2
      - ca-certificates
      - lsb-release
      - apt-transport-https
      - software-properties-common
      - wget

  handlers:
    - name: Restart SNMP Service
      systemd:
        name: snmpd
        state: restarted
        enabled: yes

    - name: Start LLDPD Service
      systemd:
        name: lldpd
        state: started
        enabled: yes

  tasks:
    - name: Update apt repositories and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Remove podman
      package:
        name: podman
        state: absent

    - name: Install each package and display debug message
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      register: package_install_result
      changed_when: package_install_result is changed
      notify:
        - Restart SNMP Service
      debug:
        msg: "Package '{{ item }}' has been installed."
      loop_control:
        label: "{{ item }}"

    - name: Download and install cockpit-sensors.deb
      apt:
        deb: /tmp/cockpit-sensors.deb
      get_url:
        url: https://github.com/ocristopfer/cockpit-sensors/releases/latest/download/cockpit-sensors.deb
        dest: /tmp/cockpit-sensors.deb

    - name: Configure SNMP Community to 'public'
      blockinfile:
        path: /etc/snmp/snmpd.conf
        block: |
          rocommunity public
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      notify: Restart SNMP Service

    - name: Check if NVM is installed
      stat:
        path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      register: nvm_installed

    - name: Install NVM (Node Version Manager)
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      when: not nvm_installed.stat.exists

    - name: Install Node.js using NVM
      shell: |
        source {{ ansible_env.HOME }}/.nvm/nvm.sh
        nvm install {{ node_version }}
      args:
        executable: /bin/bash
      when: not nvm_installed.stat.exists

    - name: Enable and Start LLDPD Service
      systemd:
        name: lldpd
        state: started
        enabled: yes
