---
- hosts: all

  become: false
  gather_facts: false
  tasks:
    - name: Connection Test
      ansible.builtin.ping:
    - name: Update all -apt
      apt:
        upgrade: yes
        update_cache: yes