---
- name: Open specified ports and confirm MTU settings
  hosts: all
  become: yes
  tasks:
    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open specific ports on firewalld
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 3300/tcp
        - 6789/tcp
        # The range 6800-6899/tcp will be handled in the next task

    - name: Open port range 6800-6899 on firewalld
      ansible.builtin.firewalld:
        port: 6800-6899/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Gather facts about network interfaces
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

