---
- name: Generate SSH key pair on each node
  hosts: all
  gather_facts: no
  vars:
    ssh_key_directory: "/tmp" # Directory to store keys temporarily

  tasks:
    - name: Check for existing SSH keys on nodes
      stat:
        path: "{{ ssh_key_directory }}/id_rsa.pub"
      register: ssh_key_check

    - name: Generate SSH key pair on each node
      openssh_keypair:
        path: "{{ ssh_key_directory }}/id_rsa"
        size: 2048
      when: not ssh_key_check.stat.exists
      register: ssh_key_info
      notify: Fetch SSH public key

  handlers:
    - name: Fetch SSH public key
      fetch:
        src: "{{ ssh_key_directory }}/id_rsa.pub"
        dest: "/tmp/id_rsa_{{ inventory_hostname }}.pub"
        flat: yes
      run_once: true

- name: Distribute public keys to all nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Assemble list of public key files
      set_fact:
        public_keys: "{{ lookup('file', item) }}"
      loop: "{{ q('fileglob', '/tmp/id_rsa_*.pub') }}"
      delegate_to: localhost
      run_once: true

    - name: Distribute public keys to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_keys }}"
