- name: Install MongoDB
  hosts: all
  gather_facts: true
  tasks:
    - name: Import the public key used by the package management system
      ansible.builtin.rpm_key:
        key: https://pgp.mongodb.com/server-7.0.asc
        state: present

    - name: Create a /etc/yum.repos.d/mongodb-org-7.0.repo file for installing MongoDB
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc

    - name: Install MongoDB packages
      ansible.builtin.yum:
        name: mongodb-org
        state: present
