- hosts: rs1
  tasks:
    - name: Stop MongoDB service
      service:
        name: mongod
        state: stopped

    - name: Set replica set and shard names
      set_fact:
        repl_set_name: rs1

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
