---
- name: Configure and Install Zscaler Private Access Connector
  hosts: all
  become: yes # to perform tasks requiring sudo

  tasks:
    - name: Create Zscaler repo file
      copy:
        dest: /etc/yum.repos.d/zscaler.repo
        content: |
          [zscaler]
          name=Zscaler Private Access Repository
          baseurl=https://yum.private.zscaler.com/yum/el7
          enabled=1
          gpgcheck=1
          gpgkey=https://yum.private.zscaler.com/gpg

    - name: Install zpa-connector
      yum:
        name: zpa-connector
        state: present

    - name: Stop zpa-connector service
      systemd:
        name: zpa-connector
        state: stopped

    - name: Create provision key file and set permissions
      file:
        path: /opt/zscaler/var/provision_key
        state: touch
        mode: "0644"

    - name: Add provision key to the file
      copy:
        dest: /opt/zscaler/var/provision_key
        content: "{{ zscaler_provision_key }}"

    - name: Start zpa-connector service
      systemd:
        name: zpa-connector
        state: started
