---
- name: Configure and Install Zscaler Private Access Connector
  hosts: all
  become: yes # to perform tasks requiring sudo

  tasks:
    - name: Create Zscaler repo file
      copy:
        dest: /etc/yum.repos.d/zscaler.repo
        content: |
          [zscaler]
          name=Zscaler Private Access Repository
          baseurl=https://yum.private.zscaler.com/yum/el7
          enabled=1
          gpgcheck=1
          gpgkey=https://yum.private.zscaler.com/gpg

    - name: Install zpa-connector
      yum:
        name: zpa-connector
        state: present

    - name: Stop zpa-connector service
      systemd:
        name: zpa-connector
        state: stopped

    - name: Create provision key file and set permissions
      file:
        path: /opt/zscaler/var/provision_key
        state: touch
        mode: "0644"

    - name: Add provision key to the file
      copy:
        dest: /opt/zscaler/var/provision_key
        content: "3|api.private.zscaler.com|3Nmfuv0hSHz2HR4vZQ8FfWzElY7VDO/OS3yj9AqBKITuhoD+KfOqZrPpuZzfzRbrfOE8TFx6e81PRdWCJotP0X3h1rkBqsD2I9wkzcSfPz+OyJMEWDJqW1/okZ6xf0H/sdY5UrVs4co6FWNJADoQrNdcbuntNE4Sifun2WFN+/ifuaXxqLNEuvJs10H4tw/DkcXH+mXOjFp3vkDMV2kY8nQp4o5Nn6gSlIWzLMXApFKwKqtWPxUz2TXpBV/OpGYru1wroAF9PBkgG2w7dznN7SSGG4H5RxBwTYlOYRCwasjdEV7qzSeDCXEwMhAyR9weudzArgthgfiW0nD6X7ZVfMLzxU3B3EghhN9/w1ENUtCSej0Xwf02dEPMuLVdOr1S"

    - name: Start zpa-connector service
      systemd:
        name: zpa-connector
        state: started
