---
- name: Update all packages, open port 27017, and reboot
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Upgrade all packages to the latest version
      dnf:
        name: "*"
        state: latest

    - name: Open TCP port 27017
      firewalld:
        port: 27017/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Open UDP port 27017
      firewalld:
        port: 27017/udp
        permanent: true
        state: enabled
        immediate: true

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting for system updates and firewall changes"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
