---
- name: Configure NFS and Mount for AlmaLinux
  hosts: all
  become: yes
  tasks:
    - name: Install nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: Add NFS ports to firewall
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 111/tcp
        - 111/udp
        - 2049/tcp
        - 2049/udp
        - 32769/tcp
        - 32769/udp

    - name: Create a directory for Telegraf config
      file:
        path: /mnt/telegraf_config
        state: directory
        mode: "0777"

    - name: Mount NFS share
      mount:
        path: /mnt/telegraf_config
        src: 192.1.0.6:/volume1/tg_config/mongocluster
        fstype: nfs
        opts: defaults
        state: mounted
        boot: yes

    - name: Change permissions on /mnt/telegraf_config
      file:
        path: /mnt/telegraf_config
        mode: "0777"
        state: directory
        recurse: yes

    - name: Modify ExecStart in telegraf.service
      lineinfile:
        path: /usr/lib/systemd/system/telegraf.service
        regexp: "^ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d"
        line: "ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /mnt/telegraf_config $TELEGRAF_OPTS"
        state: present
        backrefs: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes
