---
- name: Configure NFS and Mount for AlmaLinux
  hosts: all
  become: yes
  tasks:
    - name: Install nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: Add NFS ports to firewall
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - 111/tcp
        - 111/udp
        - 2049/tcp
        - 2049/udp
        - 32769/tcp
        - 32769/udp

    - name: Create a directory for Telegraf config
      file:
        path: /mnt/telegraf_config
        state: directory
        mode: "0755"

    - name: Mount NFS share
      mount:
        path: /mnt/telegraf_config
        src: 192.1.0.6:/volume1/tg_config/mongocluster
        fstype: nfs
        opts: defaults
        state: mounted
        boot: yes
