---
- name: Update all packages on Fedora servers
  hosts: all
  gather_facts: true
  tasks:
    - name: Upgrade all packages to the latest version
      dnf:
        name: "*"
        state: latest

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting for system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
